allowBuilds:
  '@google/genai': false
  bun: true
  esbuild: true
  protobufjs: false
minimumReleaseAgeExclude:
  - '@oven/bun-darwin-aarch64@1.4.2'
  - '@oven/bun-darwin-x64@1.4.2'
  - '@oven/bun-freebsd-aarch64@1.4.2'
  - '@oven/bun-freebsd-x64@1.4.2'
  - '@oven/bun-linux-aarch64-android@1.4.2'
  - '@oven/bun-linux-aarch64-musl@1.4.2'
  - '@oven/bun-linux-aarch64@1.4.2'
  - '@oven/bun-linux-x64-android@1.4.2'
  - '@oven/bun-linux-x64-musl@1.4.2'
  - '@oven/bun-linux-x64@1.4.2'
  - '@oven/bun-windows-aarch64@1.4.2'
  - '@oven/bun-windows-x64@1.4.2'
  - bun@1.4.2
